### ISSUE TITLE
Running iteratively 

### ISSUE THREAD

**Issue by mhkabir** [sabueso/UbntInfo#1]
Hi, 

I would like to run data acquisition continuously. 

Would you be able to give me some pointers on how to achieve this best? 

Thanks!

**Comment by sabueso** [comment]
Hi @mhkabir 

The "continuosly" part depends a lot about the frequency of the update.
Wich kind of frequency are you trying to achieve? 1sec for refresh?

Sorry for the delay to answer this issue ;)

**Comment by mhkabir** [comment]
@sabueso Yes, something like that would be nice :)

**Comment by sabueso** [comment]
@mhkabir acquire data from cgi's could be a little slow: sometimes you spent about 2 seconds to do it with UbntInfo. Let me think about it, and keep tunned into this issue ;)
